version: "3"

services:
  fastapi:
    image: event-planner-api
    build: .
    container_name: fastapi-application
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    volumes:
      - ./:/app


  database:
    image: mongo
    ports:
      - "27017"
    volumes:
      - data:/data/db

volumes:
  data: